spring:
  application:
    name: SpringBoot
    desc: Aaron SpringBoot Project
    version: 4.0.0
    packageName: com.aaron
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      pool:
        # 接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接
        max-idle: 8
        # 连接池中的最大空闲连接
        min-idle: 0

server:
  port: 8900